
defaults: &defaults
  adapter: postgresql
  username: jakepham
  password: THdp1990
  reconnect: true
  pool: 5
  wait_timeout: 5

development:
  database: jake_database
  host: localhost
  <<: *defaults

test:
  database: jake_test
  host: localhost
  <<: *defaults
  
production:
  database: jake_production
  host: localhost
  <<: *defaults